# Generated by Django 6.0.4 on 2026-05-01 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Allergies',
            },
        ),
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DietaryPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Equipment',
            },
        ),
        migrations.CreateModel(
            name='HealthGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onboarding_step', models.PositiveSmallIntegerField(default=1)),
                ('is_onboarding_complete', models.BooleanField(default=False)),
                ('language', models.CharField(default='English', max_length=50)),
                ('primary_region', models.CharField(blank=True, max_length=100)),
                ('measurement_system', models.CharField(choices=[('METRIC', 'Metric (kg, cm)'), ('IMPERIAL', 'Imperial (lb, ft/in)')], default='METRIC', max_length=10)),
                ('referral_source', models.CharField(blank=True, max_length=100)),
                ('cooking_frequency', models.CharField(blank=True, choices=[('DAILY', 'Daily'), ('FEW_TIMES_WEEK', 'A few times a week'), ('WEEKENDS', 'Only on weekends'), ('RARELY', 'Rarely')], max_length=20)),
                ('skill_level', models.CharField(blank=True, choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced'), ('PRO', 'Professional')], max_length=20)),
                ('preferred_cooking_time', models.CharField(blank=True, choices=[('UNDER_15', 'Under 15 mins'), ('UNDER_30', 'Under 30 mins'), ('UNDER_60', 'Under 60 mins'), ('ANY_TIME', 'I have plenty of time')], max_length=20)),
                ('household_size', models.CharField(blank=True, choices=[('SOLO', 'Just me'), ('COUPLE', 'Two people'), ('SMALL_FAMILY', '3-4 people'), ('LARGE_FAMILY', '5+ people')], max_length=20)),
                ('meal_planning_preference', models.CharField(blank=True, choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('FLEXIBLE', 'I am flexible')], max_length=20)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('activity_level', models.CharField(blank=True, choices=[('SEDENTARY', 'Sedentary (Little to no exercise)'), ('LIGHT', 'Lightly Active'), ('MODERATE', 'Moderately Active'), ('VERY_ACTIVE', 'Very Active'), ('EXTREME', 'Extra Active')], max_length=20)),
                ('weight_goal', models.CharField(blank=True, choices=[('LOSE', 'Lose Weight'), ('MAINTAIN', 'Maintain Weight'), ('GAIN', 'Gain Weight')], max_length=20)),
                ('current_weight', models.DecimalField(blank=True, decimal_places=2, help_text='In kg or lb based on measurement_system', max_digits=5, null=True)),
                ('target_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('current_height', models.DecimalField(blank=True, decimal_places=2, help_text='In cm or inches', max_digits=5, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other'), ('PREFER_NOT_TO_SAY', 'Prefer not to say')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allergies', models.ManyToManyField(blank=True, to='userProfile.allergy')),
                ('dietary_preferences', models.ManyToManyField(blank=True, to='userProfile.dietarypreference')),
                ('disliked_ingredients', models.ManyToManyField(blank=True, to='userProfile.ingredient')),
                ('health_goals', models.ManyToManyField(blank=True, to='userProfile.healthgoal')),
                ('kitchen_equipment', models.ManyToManyField(blank=True, to='userProfile.equipment')),
                ('preferred_cuisines', models.ManyToManyField(blank=True, to='userProfile.cuisine')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
