# Generated by Django 6.0.4 on 2026-07-22 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_recipe_dislikes_recipe_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
