# Generated by Django 6.0.4 on 2026-07-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groceryitem',
            name='list_name',
            field=models.CharField(blank=True, default='Custom Items', max_length=200),
        ),
        migrations.AlterField(
            model_name='groceryitem',
            name='quantity',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
