# Generated by Django 6.0.4 on 2026-06-15 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookBook', '0001_initial'),
        ('recipe', '0002_alter_recipe_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cookbook',
            name='recipies',
        ),
        migrations.CreateModel(
            name='CookBookRecipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField(default=0)),
                ('cookbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cookbook_recipes', to='cookBook.cookbook')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_cookbooks', to='recipe.recipe')),
            ],
            options={
                'unique_together': {('cookbook', 'recipe')},
            },
        ),
        migrations.AddField(
            model_name='cookbook',
            name='recipes',
            field=models.ManyToManyField(related_name='cookbooks', through='cookBook.CookBookRecipes', to='recipe.recipe'),
        ),
        migrations.DeleteModel(
            name='CookBookRecipies',
        ),
    ]
